DROP INDEX IF EXISTS idx_custom_league_standings_group_points_updated_active;
DROP INDEX IF EXISTS idx_custom_league_standings_user_updated_active;
DROP INDEX IF EXISTS idx_custom_league_members_group_joined_active;
DROP INDEX IF EXISTS idx_custom_leagues_league_id_active;
DROP INDEX IF EXISTS idx_user_gameweek_points_league_gameweek_active;
DROP INDEX IF EXISTS idx_lineups_league_id_active;
DROP INDEX IF EXISTS idx_fixtures_league_kickoff_desc_active;
