// Code generated by mockery v2.53.5. DO NOT EDIT.

package fixturemock

import (
	context "context"

	fixture "github.com/riskibarqy/fantasy-league/internal/domain/fixture"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, leagueID, fixtureID
func (_m *Repository) GetByID(ctx context.Context, leagueID string, fixtureID string) (fixture.Fixture, bool, error) {
	ret := _m.Called(ctx, leagueID, fixtureID)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 fixture.Fixture
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) (fixture.Fixture, bool, error)); ok {
		return rf(ctx, leagueID, fixtureID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string) fixture.Fixture); ok {
		r0 = rf(ctx, leagueID, fixtureID)
	} else {
		r0 = ret.Get(0).(fixture.Fixture)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string) bool); ok {
		r1 = rf(ctx, leagueID, fixtureID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, string, string) error); ok {
		r2 = rf(ctx, leagueID, fixtureID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListByLeague provides a mock function with given fields: ctx, leagueID
func (_m *Repository) ListByLeague(ctx context.Context, leagueID string) ([]fixture.Fixture, error) {
	ret := _m.Called(ctx, leagueID)

	if len(ret) == 0 {
		panic("no return value specified for ListByLeague")
	}

	var r0 []fixture.Fixture
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]fixture.Fixture, error)); ok {
		return rf(ctx, leagueID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []fixture.Fixture); ok {
		r0 = rf(ctx, leagueID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]fixture.Fixture)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, leagueID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
